from .heuristics import rank_candidates
from .premises import PremisesIndex


def rank_tactics(proof_goal, suggested_tactics, selected_premises=None):
    """
    Reorder suggested Isabelle tactics so the most promising ones are tried first.

    Input:
        proof_goal: the current Isabelle goal as text
        suggested_tactics: tactic candidates generated by the LLM
        selected_premises: optional relevant premises/facts

    Output:
        tactic candidates ordered from most promising to least promising
    """
    unique_tactics = []
    seen = set()

    for tactic in suggested_tactics:
        tactic = tactic.strip()

        if tactic and tactic not in seen:
            unique_tactics.append(tactic)
            seen.add(tactic)

    return rank_candidates(
        cands=unique_tactics,
        goal=proof_goal,
        state_hint="",
        facts=selected_premises or [],
        reranker=None,
        depth=0,
    )


def select_premises(proof_goal, available_premises, max_premises=5):
    """
    Select the most relevant premises/facts for the current Isabelle/HOL goal.

    Input:
        proof_goal: the current Isabelle goal as text
        available_premises: database/list of available facts, lemmas, or theorems
        max_premises: maximum number of premises to return

    Output:
        top-k relevant premises
    """
    index = PremisesIndex()

    for i, premise in enumerate(available_premises):
        index.add(f"premise_{i}", premise)

    index.finalize()

    picks = index.select(
        proof_goal,
        k_select=max_premises,
        k_rerank=max_premises,
    )

    selected_ids = [fact_id for fact_id, _select_score, _rerank_score in picks]

    return index.texts_for(selected_ids)